import { PIXEL_PALETTE, SPRITES } from "@/data/sprites";

/**
 * Pixel-art project covers.
 *
 * Every project renders from the same scene — dot grid, glow, dithered
 * ground, corner reticles — with a 16x16 sprite at the centre, so the
 * /projects grid reads as one set and matches the walking robot sprite.
 * Sprites live in data/sprites.ts (generated by scripts/gen_sprites.py).
 */

const SCENE_W = 96;
const SCENE_H = 54;
const PX = 2; // scene units per sprite pixel
const SPRITE = 16 * PX;
const OX = (SCENE_W - SPRITE) / 2; // 32
const OY = (SCENE_H - SPRITE) / 2; // 11

type Run = { x: number; y: number; w: number; fill: string };

/** Merge horizontal runs of one colour into single rects. */
function runs(rows: string[]): Run[] {
  const out: Run[] = [];
  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const c = row[x];
      if (c === ".") {
        x++;
        continue;
      }
      let w = 1;
      while (x + w < row.length && row[x + w] === c) w++;
      const fill = PIXEL_PALETTE[c];
      if (fill) out.push({ x, y, w, fill });
      x += w;
    }
  });
  return out;
}

function seeded(seed: string) {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return () => {
    h += 0x6d2b79f5;
    let t = h;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export default function CoverArt({
  seed,
  label,
  year,
  variant = "card",
  className = "",
}: {
  seed: string;
  label?: string;
  year?: string;
  variant?: "card" | "hero";
  className?: string;
}) {
  const rows = SPRITES[seed] ?? SPRITES["mastani-fetch"];
  const rand = seeded(seed);

  // A few background motes, placed off the sprite so they never fight it.
  const motes = Array.from({ length: 14 }, () => {
    const x = Math.floor(rand() * (SCENE_W / 2)) * 2;
    const y = Math.floor(rand() * (SCENE_H / 2)) * 2;
    const near = x > OX - 6 && x < OX + SPRITE + 6 && y > OY - 6 && y < OY + SPRITE + 6;
    return near ? null : { x, y, o: 0.18 + rand() * 0.3 };
  }).filter(Boolean) as { x: number; y: number; o: number }[];

  const isHero = variant === "hero";

  return (
    <div className={`relative h-full w-full overflow-hidden bg-[#070c15] ${className}`}>
      <svg
        viewBox={`0 0 ${SCENE_W} ${SCENE_H}`}
        preserveAspectRatio="xMidYMid slice"
        className="absolute inset-0 h-full w-full"
        shapeRendering="crispEdges"
        aria-hidden="true"
      >
        <defs>
          <pattern id={`dots-${seed}`} width="6" height="6" patternUnits="userSpaceOnUse">
            <rect width="1" height="1" fill="rgba(148,178,214,0.16)" />
          </pattern>
          <radialGradient id={`halo-${seed}`} cx="50%" cy="46%" r="52%">
            <stop offset="0%" stopColor="#22d3ee" stopOpacity="0.22" />
            <stop offset="100%" stopColor="#22d3ee" stopOpacity="0" />
          </radialGradient>
        </defs>

        <rect width={SCENE_W} height={SCENE_H} fill={`url(#dots-${seed})`} />
        <rect width={SCENE_W} height={SCENE_H} fill={`url(#halo-${seed})`} />

        {motes.map((m, i) => (
          <rect
            key={i}
            x={m.x}
            y={m.y}
            width="1"
            height="1"
            fill="#67e8f9"
            opacity={m.o}
          />
        ))}

        {/* dithered ground under the sprite */}
        {Array.from({ length: 13 }, (_, i) => (
          <rect
            key={i}
            x={OX - 2 + i * 3}
            y={OY + SPRITE + 2}
            width="2"
            height="1"
            fill="#22d3ee"
            opacity={i % 2 ? 0.16 : 0.34}
          />
        ))}

        {/* sprite */}
        <g>
          {runs(rows).map((r, i) => (
            <rect
              key={i}
              x={OX + r.x * PX}
              y={OY + r.y * PX}
              width={r.w * PX}
              height={PX}
              fill={r.fill}
            />
          ))}
        </g>

        {/* corner reticles, drawn in whole pixels */}
        <g fill="#22d3ee" opacity="0.4">
          <rect x="3" y="3" width="7" height="1" />
          <rect x="3" y="3" width="1" height="7" />
          <rect x={SCENE_W - 10} y="3" width="7" height="1" />
          <rect x={SCENE_W - 4} y="3" width="1" height="7" />
          <rect x="3" y={SCENE_H - 4} width="7" height="1" />
          <rect x="3" y={SCENE_H - 10} width="1" height="7" />
          <rect x={SCENE_W - 10} y={SCENE_H - 4} width="7" height="1" />
          <rect x={SCENE_W - 4} y={SCENE_H - 10} width="1" height="7" />
        </g>
      </svg>

      {/* mono readout */}
      <div
        className={`absolute inset-x-0 bottom-0 flex items-end justify-between px-4 ${
          isHero ? "pb-4" : "pb-3"
        }`}
      >
        {label && <span className="label text-[10px] text-cyan-300/70">{label}</span>}
        {year && <span className="label text-[10px] text-slate-500">{year}</span>}
      </div>

      <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#05070d] via-transparent to-transparent" />
    </div>
  );
}
